spring:
  application:
    name: SpringToDo
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: DBPASSWORD
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
